//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportInfoService.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NamesOfVariables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NamesOfVariables() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransportInfoService.Resources.NamesOfVariables", typeof(NamesOfVariables).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ArrivalTimeDayCheckBox.
        /// </summary>
        public static string CheckBoxArrivalTimeDayName {
            get {
                return ResourceManager.GetString("CheckBoxArrivalTimeDayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ArrivalTimeEveningCheckBox.
        /// </summary>
        public static string CheckBoxArrivalTimeEveningName {
            get {
                return ResourceManager.GetString("CheckBoxArrivalTimeEveningName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ArrivalTimeMorningCheckBox.
        /// </summary>
        public static string CheckBoxArrivalTimeMorningName {
            get {
                return ResourceManager.GetString("CheckBoxArrivalTimeMorningName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ArrivalTimeNightCheckBox.
        /// </summary>
        public static string CheckBoxArrivalTimeNightName {
            get {
                return ResourceManager.GetString("CheckBoxArrivalTimeNightName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DepartureTimeDayCheckBox.
        /// </summary>
        public static string CheckBoxDepartureTimeDayName {
            get {
                return ResourceManager.GetString("CheckBoxDepartureTimeDayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DepartureTimeEveningCheckBox.
        /// </summary>
        public static string CheckBoxDepartureTimeEveningName {
            get {
                return ResourceManager.GetString("CheckBoxDepartureTimeEveningName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DepartureTimeMorningCheckBox.
        /// </summary>
        public static string CheckBoxDepartureTimeMorningName {
            get {
                return ResourceManager.GetString("CheckBoxDepartureTimeMorningName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DepartureTimeNightCheckBox.
        /// </summary>
        public static string CheckBoxDepartureTimeNightName {
            get {
                return ResourceManager.GetString("CheckBoxDepartureTimeNightName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TrainTypeBusinessCheckBox.
        /// </summary>
        public static string CheckBoxTypeOfTrainBusinessName {
            get {
                return ResourceManager.GetString("CheckBoxTypeOfTrainBusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TrainTypeEconomCheckBox.
        /// </summary>
        public static string CheckBoxTypeOfTrainEconomName {
            get {
                return ResourceManager.GetString("CheckBoxTypeOfTrainEconomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DepartureStationComboBox.
        /// </summary>
        public static string ComboBoxDepartureStationName {
            get {
                return ResourceManager.GetString("ComboBoxDepartureStationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DestinationStationComboBox.
        /// </summary>
        public static string ComboBoxDestinationStationName {
            get {
                return ResourceManager.GetString("ComboBoxDestinationStationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TransportDBConnectionNewVersion.
        /// </summary>
        public static string ConnectionStringNewVersion {
            get {
                return ResourceManager.GetString("ConnectionStringNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TransportDBconnectionOldVersion.
        /// </summary>
        public static string ConnectionStringOldVersion {
            get {
                return ResourceManager.GetString("ConnectionStringOldVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TransportDBConnectionPrepodServer.
        /// </summary>
        public static string ConnectionStringPrepodServer {
            get {
                return ResourceManager.GetString("ConnectionStringPrepodServer", resourceCulture);
            }
        }
    }
}
