//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportInfoService.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransportInfoService.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подобрать.
        /// </summary>
        public static string ButtonApplyFiltersForTrains {
            get {
                return ResourceManager.GetString("ButtonApplyFiltersForTrains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найти.
        /// </summary>
        public static string ButtonSearchTrains {
            get {
                return ResourceManager.GetString("ButtonSearchTrains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На все дни.
        /// </summary>
        public static string CheckBoxAllDays {
            get {
                return ResourceManager.GetString("CheckBoxAllDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to День (с 12.00 - 17.59).
        /// </summary>
        public static string CheckBoxesDay {
            get {
                return ResourceManager.GetString("CheckBoxesDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вечер (с 18.00 - 23.59).
        /// </summary>
        public static string CheckBoxesEvening {
            get {
                return ResourceManager.GetString("CheckBoxesEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Утро (с 06.00 - 11.59).
        /// </summary>
        public static string CheckBoxesMorning {
            get {
                return ResourceManager.GetString("CheckBoxesMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ночь (с 00.00 - 05.59).
        /// </summary>
        public static string CheckBoxesNight {
            get {
                return ResourceManager.GetString("CheckBoxesNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бизнес-класс.
        /// </summary>
        public static string CheckBoxTrainTypeBusiness {
            get {
                return ResourceManager.GetString("CheckBoxTrainTypeBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эконом-класс.
        /// </summary>
        public static string CheckBoxTrainTypeEconom {
            get {
                return ResourceManager.GetString("CheckBoxTrainTypeEconom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начните вводить название станции.
        /// </summary>
        public static string ComboBoxChooseStation {
            get {
                return ResourceManager.GetString("ComboBoxChooseStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идет подбор поездов....
        /// </summary>
        public static string LabelApplyingOfFilters {
            get {
                return ResourceManager.GetString("LabelApplyingOfFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Откуда.
        /// </summary>
        public static string LabelDepartureStation {
            get {
                return ResourceManager.GetString("LabelDepartureStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Куда.
        /// </summary>
        public static string LabelDestinationStation {
            get {
                return ResourceManager.GetString("LabelDestinationStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось найти подходящий поезд!.
        /// </summary>
        public static string LabelProgramStateFail {
            get {
                return ResourceManager.GetString("LabelProgramStateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово!.
        /// </summary>
        public static string LabelProgramStateReady {
            get {
                return ResourceManager.GetString("LabelProgramStateReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подождите....
        /// </summary>
        public static string LabelProgramStateWait {
            get {
                return ResourceManager.GetString("LabelProgramStateWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Станция не найдена!.
        /// </summary>
        public static string LabelsStationNotFound {
            get {
                return ResourceManager.GetString("LabelsStationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПОДОБРАТЬ ПОЕЗД.
        /// </summary>
        public static string LabelTrainFilters {
            get {
                return ResourceManager.GetString("LabelTrainFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПО ВРЕМЕНИ.
        /// </summary>
        public static string LabelTrainTimeFilters {
            get {
                return ResourceManager.GetString("LabelTrainTimeFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПО ТИПУ.
        /// </summary>
        public static string LabelTrainTypeFilters {
            get {
                return ResourceManager.GetString("LabelTrainTypeFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправление.
        /// </summary>
        public static string TabItemDepartureTime {
            get {
                return ResourceManager.GetString("TabItemDepartureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прибытие.
        /// </summary>
        public static string TabItemDestinationTime {
            get {
                return ResourceManager.GetString("TabItemDestinationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загружаются станции....
        /// </summary>
        public static string TextStationStillLoading {
            get {
                return ResourceManager.GetString("TextStationStillLoading", resourceCulture);
            }
        }
    }
}
